// components/react.ts — compile component blueprints to React + Tailwind .tsx.
//
// Pure (schema) => FileOutput[], deterministic. One typed function component per
// blueprint: a `base` class list from the base tokens, a per-variant class map,
// and responsive `breakpoint:` prefixes from the blueprint's responsive cascade.
// Token refs become token classes (`bg-primary`); the generated code never emits
// raw hex, so it is drift-free by construction.

import type { DesignSystemSchema, ComponentBlueprint, PropDefinition } from '../types/schema.js'
import type { FileOutput } from '../types/compiler.js'
import { orderBreakpoints, type BreakpointLayer } from '../resolveResponsive.js'
import { tokenToClass, orderedProps, pascal } from './shared.js'

const HEADER = [
  '// Generated by design-spec — do not edit by hand.',
  '// Source of truth: design-spec.schema.json. Run `design-spec compile` to regenerate.',
]

/** Tailwind class list for a token group, ordered + prefixed (e.g. `md:`). */
function classList(group: Record<string, unknown>, prefix = ''): string[] {
  const out: string[] = []
  for (const prop of orderedProps(group)) {
    const cls = tokenToClass(prop, group[prop])
    if (cls) out.push(prefix ? `${prefix}:${cls}` : cls)
  }
  return out
}

/** Responsive classes for a blueprint's base, ordered mobile-first. */
function responsiveClasses(schema: DesignSystemSchema, bp: ComponentBlueprint): string[] {
  const responsive = bp.responsive as Record<string, BreakpointLayer> | undefined
  const out: string[] = []
  for (const { name, layer } of orderBreakpoints(schema, responsive)) {
    if (layer.tokens) out.push(...classList(layer.tokens as Record<string, unknown>, name))
  }
  return out
}

const TS_TYPE: Record<PropDefinition['type'], (d: PropDefinition) => string> = {
  string: () => 'string',
  boolean: () => 'boolean',
  number: () => 'number',
  enum: (d) => (d.values ?? []).map((v) => `'${v}'`).join(' | ') || 'string',
  slot: () => 'React.ReactNode',
}

function propLines(props: Record<string, PropDefinition>): string[] {
  return Object.entries(props)
    .filter(([name]) => name !== 'children')
    .map(([name, def]) => {
      const optional = def.required ? '' : '?'
      return `  ${name}${optional}: ${TS_TYPE[def.type](def)}`
    })
}

export interface ElementShape {
  tag: string
  attrs: string
  void: boolean
}

export function elementFor(bp: ComponentBlueprint): ElementShape {
  switch (bp.category) {
    case 'action':
      return { tag: 'button', attrs: 'React.ButtonHTMLAttributes<HTMLButtonElement>', void: false }
    case 'form':
      return { tag: 'input', attrs: 'React.InputHTMLAttributes<HTMLInputElement>', void: true }
    default:
      return { tag: 'div', attrs: 'React.HTMLAttributes<HTMLDivElement>', void: false }
  }
}

/** Prop interface lines for a blueprint (children excluded — it's the slot). */
export { propLines }

/** Tailwind class parts for a blueprint — reused by the Vue+Tailwind emitter. */
export function tailwindClasses(
  schema: DesignSystemSchema,
  bp: ComponentBlueprint,
): { base: string[]; variants: Record<string, string[]> } {
  const base = [...classList(bp.tokens.base as Record<string, unknown>), ...responsiveClasses(schema, bp)]
  const variants: Record<string, string[]> = {}
  if (bp.variants.length > 1) {
    for (const v of bp.variants) variants[v] = classList((bp.tokens[v] as Record<string, unknown> | undefined) ?? {})
  }
  return { base, variants }
}

function compileOne(schema: DesignSystemSchema, bp: ComponentBlueprint): FileOutput {
  const Name = pascal(bp.name)
  const el = elementFor(bp)
  const multiVariant = bp.variants.length > 1
  const hasChildren = !el.void && 'children' in bp.props

  const { base } = tailwindClasses(schema, bp)

  const lines: string[] = [...HEADER, '', "import React from 'react'", '']

  if (multiVariant) {
    lines.push(`export type ${Name}Variant = ${bp.variants.map((v) => `'${v}'`).join(' | ')}`, '')
  }

  // Props interface — `variant` plus the blueprint's own props (children excluded;
  // it comes from the slot below). `size`/state props are runtime concerns the
  // blueprint doesn't tokenize, so they aren't surfaced here.
  lines.push(`export interface ${Name}Props extends ${el.attrs} {`)
  if (multiVariant) lines.push(`  variant?: ${Name}Variant`)
  lines.push(...propLines(bp.props))
  lines.push('}')

  // base + per-variant class maps.
  lines.push('', `const base = '${base.join(' ')}'`)
  if (multiVariant) {
    lines.push('', `const variants: Record<${Name}Variant, string> = {`)
    for (const v of bp.variants) {
      const group = (bp.tokens[v] as Record<string, unknown> | undefined) ?? {}
      lines.push(`  ${v}: '${classList(group).join(' ')}',`)
    }
    lines.push('}')
  }

  // Component function — destructure only what we consume; the rest spreads onto the element.
  const destructured = [
    ...(multiVariant ? [`variant = '${bp.variants[0]}'`] : []),
    ...(hasChildren ? ['children'] : []),
    'className',
    '...props',
  ]
  const variantClass = multiVariant ? ', variants[variant]' : ''

  lines.push('', `export function ${Name}({ ${destructured.join(', ')} }: ${Name}Props) {`)
  lines.push(`  const classes = [base${variantClass}, className].filter(Boolean).join(' ')`)
  if (hasChildren) {
    lines.push(`  return <${el.tag} className={classes} {...props}>{children}</${el.tag}>`)
  } else {
    lines.push(`  return <${el.tag} className={classes} {...props} />`)
  }
  lines.push('}', '')

  return { filename: `components/react-tailwind/${Name}.tsx`, content: lines.join('\n'), language: 'tsx' }
}

/** Compile every blueprint to a React + Tailwind component file. */
export function compileReactComponents(schema: DesignSystemSchema): FileOutput[] {
  return Object.values(schema.componentBlueprints).map((bp) => compileOne(schema, bp))
}
