// components/reactCss.ts — compile blueprints to React + plain CSS (variables +
// className). Each blueprint emits a typed .tsx that references semantic classes
// and a co-located .css whose rules resolve to `var(--token)` (the same CSS the
// Vue scoped-style emitter produces). Pure (schema) => FileOutput[], deterministic.

import type { DesignSystemSchema, ComponentBlueprint } from '../types/schema.js'
import type { FileOutput } from '../types/compiler.js'
import { pascal } from './shared.js'
import { elementFor, propLines } from './react.js'
import { kebab, cssRuleBlocks } from './vue.js'

const HEADER = [
  '// Generated by design-spec — do not edit by hand.',
  '// Source of truth: design-spec.schema.json. Run `design-spec compile` to regenerate.',
]
const CSS_HEADER = [
  '/* Generated by design-spec — do not edit by hand. */',
  '/* Source of truth: design-spec.schema.json. Run `design-spec compile` to regenerate. */',
]

function compileTsx(bp: ComponentBlueprint): FileOutput {
  const Name = pascal(bp.name)
  const cls = kebab(bp.name)
  const el = elementFor(bp)
  const multiVariant = bp.variants.length > 1
  const hasChildren = !el.void && 'children' in bp.props

  const lines: string[] = [...HEADER, '', "import React from 'react'", `import './${Name}.css'`, '']

  if (multiVariant) {
    lines.push(`export type ${Name}Variant = ${bp.variants.map((v) => `'${v}'`).join(' | ')}`, '')
  }

  lines.push(`export interface ${Name}Props extends ${el.attrs} {`)
  if (multiVariant) lines.push(`  variant?: ${Name}Variant`)
  lines.push(...propLines(bp.props))
  lines.push('}')

  // Semantic class names that the .css file styles via var(--token).
  if (multiVariant) {
    lines.push('', `const variants: Record<${Name}Variant, string> = {`)
    for (const v of bp.variants) lines.push(`  ${v}: '${cls}--${v}',`)
    lines.push('}')
  }

  const destructured = [
    ...(multiVariant ? [`variant = '${bp.variants[0]}'`] : []),
    ...(hasChildren ? ['children'] : []),
    'className',
    '...props',
  ]
  const variantClass = multiVariant ? ', variants[variant]' : ''

  lines.push('', `export function ${Name}({ ${destructured.join(', ')} }: ${Name}Props) {`)
  lines.push(`  const classes = ['${cls}'${variantClass}, className].filter(Boolean).join(' ')`)
  if (hasChildren) {
    lines.push(`  return <${el.tag} className={classes} {...props}>{children}</${el.tag}>`)
  } else {
    lines.push(`  return <${el.tag} className={classes} {...props} />`)
  }
  lines.push('}', '')

  return { filename: `components/react-css/${Name}.tsx`, content: lines.join('\n'), language: 'tsx' }
}

function compileCss(schema: DesignSystemSchema, bp: ComponentBlueprint): FileOutput {
  const Name = pascal(bp.name)
  const cls = kebab(bp.name)
  const cssPrefix = schema.export.cssVariablePrefix
  const content = [...CSS_HEADER, '', ...cssRuleBlocks(schema, bp, cls, cssPrefix), ''].join('\n')
  return { filename: `components/react-css/${Name}.css`, content, language: 'css' }
}

/** Compile every blueprint to a React + CSS (.tsx + .css) pair. */
export function compileReactCssComponents(schema: DesignSystemSchema): FileOutput[] {
  return Object.values(schema.componentBlueprints).flatMap((bp) => [compileTsx(bp), compileCss(schema, bp)])
}
