// components/vue.ts — compile component blueprints to Vue 3 SFCs (scoped CSS).
//
// Pure (schema) => FileOutput[], deterministic. One `.vue` single-file component
// per blueprint: typed `defineProps`, a slot (or void element), and a scoped
// `<style>` block where token refs become `var(--…)` declarations and the
// responsive cascade becomes mobile-first `@media (min-width: …)` blocks.

import type { DesignSystemSchema, ComponentBlueprint, PropDefinition } from '../types/schema.js'
import type { FileOutput } from '../types/compiler.js'
import { orderBreakpoints, type BreakpointLayer } from '../resolveResponsive.js'
import { tokenToCss, orderedProps, pascal } from './shared.js'

const HEADER = [
  '<!-- Generated by design-spec — do not edit by hand. -->',
  '<!-- Source of truth: design-spec.schema.json. Run `design-spec compile` to regenerate. -->',
]

const TS_TYPE: Record<PropDefinition['type'], (d: PropDefinition) => string> = {
  string: () => 'string',
  boolean: () => 'boolean',
  number: () => 'number',
  enum: (d) => (d.values ?? []).map((v) => `'${v}'`).join(' | ') || 'string',
  slot: () => 'unknown',
}

/** CSS declaration lines for a token group, indented two spaces. */
function declarations(group: Record<string, unknown>, cssPrefix: string): string[] {
  const out: string[] = []
  for (const prop of orderedProps(group)) {
    for (const decl of tokenToCss(prop, group[prop], cssPrefix)) out.push(`  ${decl}`)
  }
  return out
}

export function kebab(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase()
}

/**
 * CSS rule blocks for a blueprint (base `.cls`, per-variant `.cls--v`, and
 * mobile-first `@media` overrides) — no `<style>` wrapper. Shared by the Vue
 * scoped-style emitter and the React+CSS standalone `.css` emitter.
 */
export function cssRuleBlocks(
  schema: DesignSystemSchema,
  bp: ComponentBlueprint,
  cls: string,
  cssPrefix: string,
): string[] {
  const out: string[] = [`.${cls} {`, ...declarations(bp.tokens.base as Record<string, unknown>, cssPrefix), '}']
  if (bp.variants.length > 1) {
    for (const v of bp.variants) {
      const group = bp.tokens[v] as Record<string, unknown> | undefined
      if (!group) continue
      const decls = declarations(group, cssPrefix)
      if (decls.length) out.push('', `.${cls}--${v} {`, ...decls, '}')
    }
  }
  const responsive = bp.responsive as Record<string, BreakpointLayer> | undefined
  for (const { minWidth, layer } of orderBreakpoints(schema, responsive)) {
    if (!layer.tokens || minWidth === null) continue
    const decls = declarations(layer.tokens as Record<string, unknown>, cssPrefix)
    if (decls.length) out.push('', `@media (min-width: ${minWidth}) {`, `  .${cls} {`, ...decls.map((d) => `  ${d}`), '  }', '}')
  }
  return out
}

function compileOne(schema: DesignSystemSchema, bp: ComponentBlueprint): FileOutput {
  const Name = pascal(bp.name)
  const cls = kebab(bp.name)
  const cssPrefix = schema.export.cssVariablePrefix
  const multiVariant = bp.variants.length > 1
  const isVoid = bp.category === 'form'
  const hasSlot = !isVoid

  // ── <script setup> ──
  const propDefs = Object.entries(bp.props)
    .filter(([name]) => name !== 'children')
    .map(([name, def]) => `  ${name}?: ${TS_TYPE[def.type](def)}`)
  if (multiVariant) propDefs.unshift(`  variant?: ${bp.variants.map((v) => `'${v}'`).join(' | ')}`)

  const script = ['<script setup lang="ts">', 'defineProps<{', ...propDefs, '}>()', '</script>']

  // ── <template> ──
  const tag = isVoid ? 'input' : bp.category === 'action' ? 'button' : 'div'
  const classBind = multiVariant
    ? ` :class="variant ? \`${cls}--\${variant}\` : ''"`
    : ''
  const template = ['<template>']
  if (isVoid) {
    template.push(`  <${tag} class="${cls}"${classBind} />`)
  } else {
    template.push(`  <${tag} class="${cls}"${classBind}>`)
    if (hasSlot) template.push('    <slot />')
    template.push(`  </${tag}>`)
  }
  template.push('</template>')

  // ── <style scoped> ──
  const style = ['<style scoped>', ...cssRuleBlocks(schema, bp, cls, cssPrefix), '</style>']

  const content = [...HEADER, '', ...script, '', ...template, '', ...style, ''].join('\n')
  return { filename: `components/vue-css/${Name}.vue`, content, language: 'vue' }
}

/** Compile every blueprint to a Vue SFC. */
export function compileVueComponents(schema: DesignSystemSchema): FileOutput[] {
  return Object.values(schema.componentBlueprints).map((bp) => compileOne(schema, bp))
}
