// components/vueTailwind.ts — compile blueprints to Vue 3 SFCs that use Tailwind
// utility classes (no scoped CSS; relies on the generated tailwind.config.js).
// Reuses the same class builder as the React+Tailwind emitter so the two stay in
// lockstep. Pure (schema) => FileOutput[], deterministic.

import type { DesignSystemSchema, ComponentBlueprint, PropDefinition } from '../types/schema.js'
import type { FileOutput } from '../types/compiler.js'
import { pascal } from './shared.js'
import { tailwindClasses } from './react.js'

const HEADER = [
  '<!-- Generated by design-spec — do not edit by hand. -->',
  '<!-- Source of truth: design-spec.schema.json. Run `design-spec compile` to regenerate. -->',
]

const TS_TYPE: Record<PropDefinition['type'], (d: PropDefinition) => string> = {
  string: () => 'string',
  boolean: () => 'boolean',
  number: () => 'number',
  enum: (d) => (d.values ?? []).map((v) => `'${v}'`).join(' | ') || 'string',
  slot: () => 'unknown',
}

function compileOne(schema: DesignSystemSchema, bp: ComponentBlueprint): FileOutput {
  const Name = pascal(bp.name)
  const isVoid = bp.category === 'form'
  const tag = isVoid ? 'input' : bp.category === 'action' ? 'button' : 'div'
  const multiVariant = bp.variants.length > 1
  const { base, variants } = tailwindClasses(schema, bp)
  const baseClass = base.join(' ')

  // ── <script setup> ──
  const propDefs = Object.entries(bp.props)
    .filter(([name]) => name !== 'children')
    .map(([name, def]) => `  ${name}?: ${TS_TYPE[def.type](def)}`)
  if (multiVariant) propDefs.unshift(`  variant?: ${bp.variants.map((v) => `'${v}'`).join(' | ')}`)

  const script: string[] = ['<script setup lang="ts">']
  if (multiVariant) {
    script.push("import { computed } from 'vue'")
    script.push(`const props = withDefaults(defineProps<{`, ...propDefs, `}>(), { variant: '${bp.variants[0]}' })`)
    script.push('const variantClasses: Record<string, string> = {')
    for (const v of bp.variants) script.push(`  ${v}: '${variants[v].join(' ')}',`)
    script.push('}')
    script.push(`const classes = computed(() => '${baseClass}' + ' ' + (variantClasses[props.variant ?? '${bp.variants[0]}'] ?? ''))`)
  } else if (propDefs.length) {
    script.push('defineProps<{', ...propDefs, '}>()')
  }
  script.push('</script>')

  // ── <template> ──
  const classAttr = multiVariant ? ':class="classes"' : `class="${baseClass}"`
  const template = ['<template>']
  if (isVoid) {
    template.push(`  <${tag} ${classAttr} />`)
  } else {
    template.push(`  <${tag} ${classAttr}>`, '    <slot />', `  </${tag}>`)
  }
  template.push('</template>')

  const content = [...HEADER, '', ...script, '', ...template, ''].join('\n')
  return { filename: `components/vue-tailwind/${Name}.vue`, content, language: 'vue' }
}

/** Compile every blueprint to a Vue + Tailwind SFC. */
export function compileVueTailwindComponents(schema: DesignSystemSchema): FileOutput[] {
  return Object.values(schema.componentBlueprints).map((bp) => compileOne(schema, bp))
}
