// cssVars.ts — the single CSS-custom-property emitter for tokens.css.
//
// Both the Tailwind and the Vue compilers emit the same `tokens.css`; sharing one
// emitter keeps them from drifting. Pure, deterministic, insertion-order stable.
// Naming convention (with the configured `cssVariablePrefix` p):
//   --{p}color-{n}  --{p}spacing-{n}  --{p}rounded-{n}  --{p}shadow-{n}
//   --{p}border-width-{n}  --{p}border-color-{n}
//   --{p}font-{n}-{family|size|weight|line-height}
//   --{p}opacity-{n}  --{p}duration-{n}  --{p}ease-{n}
// These are exactly the names the component compilers reference via tokenToCss.

import type { DesignSystemSchema } from './types/schema.js'
import { resolveValue } from './tokenResolver.js'

function px(v: unknown): string {
  return typeof v === 'number' ? `${v}px` : String(v)
}

/** All token groups as `--var: value;` lines (no `:root{}` wrapper, no indent). */
export function cssVarLines(schema: DesignSystemSchema): string[] {
  const p = schema.export.cssVariablePrefix
  const lines: string[] = []

  for (const [n, hex] of Object.entries(schema.colors)) lines.push(`--${p}color-${n}: ${hex};`)
  for (const [n, v] of Object.entries(schema.spacing)) lines.push(`--${p}spacing-${n}: ${px(v)};`)
  for (const [n, v] of Object.entries(schema.rounded)) lines.push(`--${p}rounded-${n}: ${px(v)};`)
  for (const [n, s] of Object.entries(schema.shadows)) {
    lines.push(`--${p}shadow-${n}: ${Array.isArray(s.value) ? s.value.join(', ') : s.value};`)
  }
  for (const [n, v] of Object.entries(schema.borders.width)) lines.push(`--${p}border-width-${n}: ${px(v)};`)
  for (const [n, v] of Object.entries(schema.borders.color)) {
    lines.push(`--${p}border-color-${n}: ${String(resolveValue(schema, v))};`)
  }
  for (const [n, t] of Object.entries(schema.typography)) {
    lines.push(`--${p}font-${n}-family: ${t.fontFamily};`)
    lines.push(`--${p}font-${n}-size: ${px(t.fontSize)};`)
    lines.push(`--${p}font-${n}-weight: ${t.fontWeight};`)
    lines.push(`--${p}font-${n}-line-height: ${String(t.lineHeight)};`)
  }
  for (const [n, v] of Object.entries(schema.opacity)) lines.push(`--${p}opacity-${n}: ${v};`)
  for (const [n, v] of Object.entries(schema.transitions.duration)) lines.push(`--${p}duration-${n}: ${v};`)
  for (const [n, v] of Object.entries(schema.transitions.easing)) lines.push(`--${p}ease-${n}: ${v};`)

  return lines
}

/** A complete `tokens.css` document string with the generated-file banner. */
export function tokensCss(schema: DesignSystemSchema): string {
  return [
    '/* Generated by design-spec — do not edit by hand. */',
    '/* Source of truth: design-spec.schema.json. Run `design-spec compile` to regenerate. */',
    ':root {',
    ...cssVarLines(schema).map((l) => `  ${l}`),
    '}',
    '',
  ].join('\n')
}
