// tailwind.ts — compile a schema to tailwind.config.js + tokens.css.
//
// Pure (schema) => FileOutput[], deterministic. Emits a Tailwind theme keyed by
// the schema's token names plus a tokens.css of CSS custom properties. Phase 1
// working-minimal; Phase 2 hardens with golden snapshots.

import type { DesignSystemSchema } from './types/schema.js'
import type { FileOutput } from './types/compiler.js'
import { resolveValue } from './tokenResolver.js'
import { tokensCss } from './cssVars.js'

function px(v: unknown): string {
  return typeof v === 'number' ? `${v}px` : String(v)
}

/** `'key': 'value',` lines for one theme group, two extra indent levels. */
function entries(pairs: Array<[string, string]>): string {
  return pairs.map(([k, v]) => `        '${k}': '${v}',`).join('\n')
}

function themeObject(schema: DesignSystemSchema): string {
  const p = schema.export.cssVariablePrefix
  const mapColors = entries(Object.keys(schema.colors).map((n) => [n, `var(--${p}color-${n})`]))
  const mapSpacing = entries(Object.keys(schema.spacing).map((n) => [n, `var(--${p}spacing-${n})`]))
  const mapRounded = entries(Object.keys(schema.rounded).map((n) => [n, `var(--${p}rounded-${n})`]))
  const mapBorderWidth = entries(Object.keys(schema.borders.width).map((n) => [n, `var(--${p}border-width-${n})`]))
  const mapShadow = entries(Object.keys(schema.shadows).map((n) => [n, `var(--${p}shadow-${n})`]))
  const mapScreens = entries(Object.entries(schema.breakpoints).map(([n, v]) => [n, px(v)]))
  const mapFont = Object.entries(schema.typography)
    .map(([name, t]) => {
      const fs = px(resolveValue(schema, t.fontSize))
      return `        '${name}': ['${fs}', { lineHeight: '${String(t.lineHeight)}', fontWeight: '${t.fontWeight}' }],`
    })
    .join('\n')

  return [
    '    extend: {',
    '      screens: {',
    mapScreens,
    '      },',
    '      colors: {',
    mapColors,
    '      },',
    '      spacing: {',
    mapSpacing,
    '      },',
    '      borderRadius: {',
    mapRounded,
    '      },',
    '      borderWidth: {',
    mapBorderWidth,
    '      },',
    '      boxShadow: {',
    mapShadow,
    '      },',
    '      fontSize: {',
    mapFont,
    '      },',
    '    },',
  ].join('\n')
}

export function compileTailwind(schema: DesignSystemSchema): FileOutput[] {
  const prefix = schema.export.tailwindClassPrefix
  const config = [
    '// Generated by design-spec — do not edit by hand.',
    '// Source of truth: design-spec.schema.json. Run `design-spec compile` to regenerate.',
    '/** @type {import("tailwindcss").Config} */',
    'export default {',
    `  prefix: '${prefix}',`,
    "  content: ['./src/**/*.{js,ts,jsx,tsx,vue,html}'],",
    '  theme: {',
    themeObject(schema),
    '  },',
    '  plugins: [],',
    '}',
    '',
  ].join('\n')

  return [
    { filename: 'tailwind.config.js', content: config, language: 'javascript' },
    { filename: 'tokens.css', content: tokensCss(schema), language: 'css' },
  ]
}
