// tailwind.ts — compile a schema to tailwind.config.js + tokens.css.
//
// Pure (schema) => FileOutput[], deterministic. Emits a Tailwind theme keyed by
// the schema's token names plus a tokens.css of CSS custom properties. Phase 1
// working-minimal; Phase 2 hardens with golden snapshots.

import type { DesignSystemSchema } from './types/schema.js'
import type { FileOutput } from './types/compiler.js'
import { resolveValue } from './tokenResolver.js'

function px(v: unknown): string {
  return typeof v === 'number' ? `${v}px` : String(v)
}

function cssVars(schema: DesignSystemSchema): string {
  const p = schema.export.cssVariablePrefix
  const lines: string[] = []
  for (const [name, hex] of Object.entries(schema.colors)) lines.push(`  --${p}color-${name}: ${hex};`)
  for (const [name, v] of Object.entries(schema.spacing)) lines.push(`  --${p}spacing-${name}: ${px(v)};`)
  for (const [name, v] of Object.entries(schema.rounded)) lines.push(`  --${p}rounded-${name}: ${px(v)};`)
  for (const [name, s] of Object.entries(schema.shadows)) {
    const val = Array.isArray(s.value) ? s.value.join(', ') : s.value
    lines.push(`  --${p}shadow-${name}: ${val};`)
  }
  return `:root {\n${lines.join('\n')}\n}\n`
}

function themeObject(schema: DesignSystemSchema): string {
  const p = schema.export.cssVariablePrefix
  const mapColors = Object.keys(schema.colors)
    .map((name) => `        '${name}': 'var(--${p}color-${name})',`)
    .join('\n')
  const mapSpacing = Object.keys(schema.spacing)
    .map((name) => `        '${name}': 'var(--${p}spacing-${name})',`)
    .join('\n')
  const mapRounded = Object.keys(schema.rounded)
    .map((name) => `        '${name}': 'var(--${p}rounded-${name})',`)
    .join('\n')
  const mapFont = Object.entries(schema.typography)
    .map(([name, t]) => {
      const fs = px(resolveValue(schema, t.fontSize))
      return `        '${name}': ['${fs}', { lineHeight: '${String(t.lineHeight)}', fontWeight: '${t.fontWeight}' }],`
    })
    .join('\n')

  return [
    '    extend: {',
    '      colors: {',
    mapColors,
    '      },',
    '      spacing: {',
    mapSpacing,
    '      },',
    '      borderRadius: {',
    mapRounded,
    '      },',
    '      fontSize: {',
    mapFont,
    '      },',
    '    },',
  ].join('\n')
}

export function compileTailwind(schema: DesignSystemSchema): FileOutput[] {
  const prefix = schema.export.tailwindClassPrefix
  const config = [
    '// Generated by design-spec — do not edit by hand.',
    '// Source of truth: design-spec.schema.json. Run `design-spec compile` to regenerate.',
    '/** @type {import("tailwindcss").Config} */',
    'export default {',
    `  prefix: '${prefix}',`,
    "  content: ['./src/**/*.{js,ts,jsx,tsx,vue,html}'],",
    '  theme: {',
    themeObject(schema),
    '  },',
    '  plugins: [],',
    '}',
    '',
  ].join('\n')

  return [
    { filename: 'tailwind.config.js', content: config, language: 'javascript' },
    { filename: 'tokens.css', content: cssVars(schema), language: 'css' },
  ]
}
