// vue.ts — compile a schema to tokens.css custom properties for a Vue app.
//
// Pure (schema) => FileOutput[], deterministic. Vue projects consume tokens as
// plain CSS custom properties (no Tailwind theme object). Typography is emitted
// as grouped helper variables.

import type { DesignSystemSchema } from './types/schema.js'
import type { FileOutput } from './types/compiler.js'

function px(v: unknown): string {
  return typeof v === 'number' ? `${v}px` : String(v)
}

export function compileVue(schema: DesignSystemSchema): FileOutput[] {
  const p = schema.export.cssVariablePrefix
  const lines: string[] = []

  for (const [name, hex] of Object.entries(schema.colors)) lines.push(`  --${p}color-${name}: ${hex};`)
  for (const [name, v] of Object.entries(schema.spacing)) lines.push(`  --${p}spacing-${name}: ${px(v)};`)
  for (const [name, v] of Object.entries(schema.rounded)) lines.push(`  --${p}rounded-${name}: ${px(v)};`)
  for (const [name, s] of Object.entries(schema.shadows)) {
    lines.push(`  --${p}shadow-${name}: ${Array.isArray(s.value) ? s.value.join(', ') : s.value};`)
  }
  for (const [name, t] of Object.entries(schema.typography)) {
    lines.push(`  --${p}font-${name}-size: ${px(t.fontSize)};`)
    lines.push(`  --${p}font-${name}-weight: ${t.fontWeight};`)
    lines.push(`  --${p}font-${name}-line-height: ${String(t.lineHeight)};`)
    lines.push(`  --${p}font-${name}-family: ${t.fontFamily};`)
  }

  const content = [
    '/* Generated by design-spec — do not edit by hand. */',
    '/* Source of truth: design-spec.schema.json. Run `design-spec compile` to regenerate. */',
    ':root {',
    lines.join('\n'),
    '}',
    '',
  ].join('\n')

  return [{ filename: 'tokens.css', content, language: 'css' }]
}
